008 pagination
Conaill4/nodejs-express-axios pull request #21
Opened 2024-09-09 14:58 UTC by Conaill4

2024-09-10 14:47 UTC, mlynch147 commented on src/services/JobRoleService.ts
> +                throw new Error('Server Error');
update to say "Unknown Server Error"

2024-09-10 14:48 UTC, mlynch147 commented on test/unit/JobRolesServiceTests.ts
>            const token = "123";
check if used - if not, delete

2024-09-10 14:51 UTC, mlynch147 requested changes
two minor comments... great stuff

2024-09-10 14:59 UTC, Conaill4 commented on src/services/JobRoleService.ts
> +                throw new Error('Server Error');
Updated if to handle unknown errors

2024-09-10 15:00 UTC, Conaill4 commented on test/unit/JobRolesServiceTests.ts
>            const token = "123";
updated

2024-09-10 15:09 UTC, ldevlin559 approved these changes

2024-09-11 10:52 UTC, mlynch147 approved these changes

2024-09-11 10:53 UTC, merged